# Create a function to import this XML file. Your function must include appropriate exception handling clauses covering all possible error conditions and should return the parsed contents of the XML file. 

In [97]:
import xml.etree.ElementTree as ET
import pandas as pd

def import_xml(xml_file):
    xml_data=pd.read_xml(xml_file)
    return xml_data


# Using the function you created in a) above, load the XML file.

In [96]:
xml_file_path="C:/Users/User/Python_practice_scripts/Titanic.xml"
xml_dat = import_xml(xml_file_path)
print(xml_dat)

     index  PassengerId  Survived  Pclass  \
0        0            1         0       3   
1        1            2         1       1   
2        2            3         1       3   
3        3            4         1       1   
4        4            5         0       3   
..     ...          ...       ...     ...   
886    886          887         0       2   
887    887          888         1       1   
888    888          889         0       3   
889    889          890         1       1   
890    890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  

# . Then use the print() function to display the Gender and the name for the second, fourth, eighth, sixteenth, and thirty-second passengers. 

In [11]:
df = pd.DataFrame(import_xml(xml_file_path))
locations =[2,4,8,16,32]
gender_name=[]
for i in locations:
    print(df[['Sex', 'Name']].iloc[i]) 
    gender_name.append(df[['Sex', 'Name']].iloc[i])
df2=pd.DataFrame(gender_name)

Sex                     female
Name    Heikkinen, Miss. Laina
Name: 2, dtype: object
Sex                         male
Name    Allen, Mr. William Henry
Name: 4, dtype: object
Sex                                                female
Name    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
Name: 8, dtype: object
Sex                     male
Name    Rice, Master. Eugene
Name: 16, dtype: object
Sex                       female
Name    Glynn, Miss. Mary Agatha
Name: 32, dtype: object


In [12]:
print(df2)

       Sex                                               Name
2   female                             Heikkinen, Miss. Laina
4     male                           Allen, Mr. William Henry
8   female  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
16    male                               Rice, Master. Eugene
32  female                           Glynn, Miss. Mary Agatha


# Save, above extracted records in PostgreSQL database with table name ‘Passenger ’

In [112]:
import pandas as pd
import numpy as np
import os

import matplotlib.pyplot as plt
import seaborn as sn

import sqlalchemy as db

engine = db.create_engine('postgresql://postgres:7019@localhost:5432/Customer')
def write_dataset(name,dataset,engine):
    dataset.to_sql('%s' % (name),engine,index=True,if_exists='replace',chunksize=1000)

write_dataset('Passenger', df2, engine)




In [113]:
def read_dataset(name,engine):
    try:
        dataset = pd.read_sql_table(name,engine)
    except:
        dataset = pd.DataFrame([])
    return dataset
read_dataset('Passenger', engine)

index     Sex                                               Name
0      2  female                             Heikkinen, Miss. Laina
1      4    male                           Allen, Mr. William Henry
2      8  female  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
3     16    male                               Rice, Master. Eugene
4     32  female                           Glynn, Miss. Mary Agatha

# For all passengers where the age less than 30 and Class = 1 or 2, if they survived then extract the fields below and save them to a CSV file. Note that you should not use Pandas for this task.• Gender• Name• Cabin• Ticket• PassengerId

In [114]:
write_dataset('All_Passenger',df,engine)

In [115]:
from sqlalchemy import create_engine, MetaData
result=engine.execute('Select count(*) from "All_Passenger"')
for i in result:
    print("Total passangers",i)

Total passangers (891,)


In [105]:
#passengers_survived='Select "Sex","Name","Cabin","Ticket","PassengerId"  from "All_Passenger" where "Age"<30  and "Survived"==1;'
#passengers_survived_v=engine.execute(passengers_survived)
#print(pd.read_sql(passengers_survived,engine))

passengers_survived='Select "Sex","Name","Cabin","Ticket","PassengerId"  from "All_Passenger" where "Age"<30 AND "Survived"=1 AND("Pclass"=1 OR "Pclass"=2)'
print(pd.read_sql(passengers_survived, engine))

       Sex                                               Name Cabin  \
0   female                Nasser, Mrs. Nicholas (Adele Achem)  None   
1     male                       Sloper, Mr. William Thompson    A6   
2   female           Laroche, Miss. Simonne Marie Anne Andree  None   
3   female  Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkin...  None   
4   female                                  Rugg, Miss. Emily  None   
..     ...                                                ...   ...   
84  female                       Duran y More, Miss. Asuncion  None   
85  female              Abelson, Mrs. Samuel (Hannah Wizosky)  None   
86  female       Shelley, Mrs. William (Imanita Parrish Hall)  None   
87  female                       Graham, Miss. Margaret Edith   B42   
88    male                              Behr, Mr. Karl Howell  C148   

           Ticket  PassengerId  
0          237736           10  
1          113788           24  
2   SC/Paris 2123           44  
3            29

In [116]:
import numpy as np
array1=np.arange(1,28)
#("Array of all the even integers from 2000 to 4000")
#print(array)
matrix1= array1.reshape(3,3,3)
print(matrix1)


[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


# Take two 3D matrices, Matrix1 and Matrix2, each with dimensions 3x3x3. You want to perform the following operations on these matrices: (Note: use same value given below)

In [117]:
array2_1=np.arange(9,0,-1)
print(array2_1)
array2_2=np.arange(27,18,-1)
print(array2_2)
array2_3=np.arange(18,9,-1)
print(array2_3)
array2=[]
array2.append(array2_1)
array2.append(array2_2)
array2.append(array2_3)
#array2=list(array2)
array_2 = np.array(array2)
matrix2= array_2.reshape(3,3,3)
print(matrix2)

[9 8 7 6 5 4 3 2 1]
[27 26 25 24 23 22 21 20 19]
[18 17 16 15 14 13 12 11 10]
[[[ 9  8  7]
  [ 6  5  4]
  [ 3  2  1]]

 [[27 26 25]
  [24 23 22]
  [21 20 19]]

 [[18 17 16]
  [15 14 13]
  [12 11 10]]]


# Extract the diagonal from the each dimension of each matrix

In [118]:
sum_value=0
array3=[]
array4=[]
for i in range(0,3):
    for j in range(0,3):
        for k in range(0,3):
            if(j==k):
                array3.append(matrix1[i,j,k])
                array4.append(matrix2[i,j,k])
                sum_value+=matrix1[i,j,k]+matrix2[i,j,k]
print(sum_value)
print(array3)
print(array4)
matrix1_diag=np.array(array3).reshape(3,3)
matrix2_diag=np.array(array4).reshape(3,3)





252
[1, 5, 9, 10, 14, 18, 19, 23, 27]
[9, 5, 1, 27, 23, 19, 18, 14, 10]


# Take sum of diagonals obtained from Matrix1 and Matrix2 element-wise to get a new 2D

In [107]:
matrix_sum=matrix1_diag+matrix2_diag
matrix_sum

array([[10, 10, 10],
       [37, 37, 37],
       [37, 37, 37]])

# Take product of diagonals obtained from Matrix1 and Matrix2 element-wise to get a new 2D matrix.


In [71]:
matrix_product=matrix1_diag*matrix2_diag
matrix_product

array([[  9,  25,   9],
       [270, 322, 342],
       [342, 322, 270]])

# (c) Calculate the sum of all the elements in the resulting product.


In [76]:
def sumColumn(matrix):
    return np.sum(matrix, axis=1)
sum_product=sum(sumColumn(matrix_product))
sum_product


1911

# (d) Calculate the variance of the values in the flattened (1D) version of the matrices. Hint use Numpy var 

In [78]:
matrix1_variance=np.var(array1)
matrix1_variance

60.666666666666664

In [79]:
matrix2_variance=np.var(array_2)
matrix2_variance

60.666666666666664

# The function should use regular expressions to check if the string contains Valid Class C IPv4 address. Note (Class C networks range from 192.0. 0.0 through 223.255. 255.0)


In [150]:
import re
def valid_ip4(string):
    #pattern = "^((25[0-5]|2[0-4][0-9]|1[0-9][2-9]|[1-9]?[0-9])\.){3}(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])$"
    pattern_regex = r"[192-223]$"
    return bool(re.match(pattern_regex,string))
x= valid_ip4("192")
print(x)


    

False


In [121]:
import re

def is_valid_class_c (ip):
    # Class C networks range from 192.0.0.0 through 223.255.255.0
    # The first octet must be between 192 and 223
    # The other three octets must be between 0 and 255
    # The regex pattern for a valid Class C IPv4 address is:
    # ^ (192-223)\\. (0-255)\\. (0-255)\\. (0-255)$
    # We use the re.match function to check if the ip string matches the pattern
    pattern = r"^ ( (?:1 [9] [2-9]|2 [0-1] [0-9]|22 [0-3])\\. (?: [0-9] | [1-9] [0-9] |1 [0-9] [0-9]|2 [0-4] [0-9]|25 [0-5])\\. (?: [0-9] | [1-9] [0-9] |1 [0-9] [0-9]|2 [0-4] [0-9]|25 [0-5])\\. (?: [0-9] | [1-9] [0-9] |1 [0-9] [0-9]|2 [0-4] [0-9]|25 [0-5]))$"
    return bool (re.match (pattern, ip))

# Examples
print (is_valid_class_c ("192.0. 0.0")) # True
print (is_valid_class_c ("224.1.1.1")) # False
print (is_valid_class_c ("127.1.2.3")) # False
print (is_valid_class_c ("192.256.1.1")) # False
print (is_valid_class_c ("223.255. 255.0"))

False
False
False
False
False


In [127]:
#TASK3

#1. The function should use regular expressions to check if the string contains Valid Class C IPv4 address. [10
#marks] Note (Class C networks range from 192.0. 0.0 through 223.255. 255.0)
 

# IP address using Regex


import re
import ipaddress

 

# Function for Validating IP

def Validate_It(IP):

# Regex expression for validating IPv4
    regex = "^((25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\.){3}(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])$"

#Regex expression for validating IPv6
    regex1 = "((([0-9a-fA-F]){1,4})\\:){7}([0-9a-fA-F]){1,4}"
    p = re.compile(regex)
    p1 = re.compile(regex1)
    # Checking if it is a valid IPv4 addresses
    if (re.search(p, IP)):
        return "Valid IPv4"
    
    # Checking if it is a valid IPv6 addresses
    elif (re.search(p1, IP)):
            return "Valid IPv6"
    
    # Return Invalid
    return "Invalid IP"
    
 

# Driver Code

 

# IP addresses to validate
IP = "257.120.223.13"
print(Validate_It(IP))

IP = "192.0.0.0"
print(Validate_It(IP))


IP = "2F33:12a0:3Ea0:0302"
print(Validate_It(IP))


Invalid IP
Valid IPv4
Invalid IP
