**Question 1**

Theophylline is a drug used for the treatment of diseases such as chronic obstructive pulmonary disease
and asthma. This medicine was administered to 20 subjects over a number of days. Each time the drug
was administered to the subjects, the following measurements were recorded:

| field | description |
|-------|-------------|
|id | a number (1, . . . , 20) identifying the subject on whom the observation was made |
|weight|weight of the subject (kg)|
|dose|dose of theophylline administered orally to the subject (mg/kg)|
|time|time since drug administration when the sample was drawn (hr)|
|conc|theophylline concentration in the sample (mg/L)|

There are 1,000 records in total. You have been provided with an XML file containing this data.

a) Create a function to import this XML file. Your function should include exception handling
clauses.

In [1]:
import xml.etree.ElementTree as ET

xmlfile = 'theoDataset.xml'

try :
    xmldata = open(xmlfile,'r')
    xmltree = ET.fromstring(xmldata.read())
except FileNotFoundError:
    print('Could not open the file:'.format(xmlfile))
except IOError:
    print('Could not read from the file:'.format(xmlfile))
finally :
    xmldata.close()

b) Use the print function to display the ‘id’, ‘weight’ and ‘conc’ of the second, fourth, sixth, eight and tenth records in the XML dataset. (Hint: you may use the range() function). 

In [2]:
for i in range(1,10,2) :
    id = xmltree[i].find('id').text
    weight = xmltree[i].find('weight').text
    conc = xmltree[i].find('conc').text
    print('id:{}\tweight:{}\tconc:{}'.format(id,weight,conc))

id:13	weight:73.8	conc:0.66
id:5	weight:88.3	conc:9.47
id:8	weight:81.3	conc:6.43
id:10	weight:75.1	conc:11.25
id:20	weight:67.9	conc:7.84


c) Extract all the XML data and write it to a CSV file. Your file should also contain the column names.

In [3]:
import csv

csv_file = "./theodata.csv"

try :
    theo_csv = open(csv_file, 'w')
    csvwriter = csv.writer(theo_csv)
    head = []
    rowcount = 0
    for subject in xmltree.findall('subject'):
        row = []
        if rowcount == 0:
            for col in range(0,len(list(subject))) :
                head.append(subject[col].tag)
            csvwriter.writerow(head)
            rowcount = rowcount + 1
        for col in range(0,len(list(subject))) :
            row.append(subject[col].text)
        csvwriter.writerow(row)
except FileNotFoundError:
    print('Could not open the file:'.format(csv_file))
except IOError:
    print('Could not write to the file:'.format(csv_file))
finally :
    theo_csv.close()

**Question 2**

a) Create a NumPy array filled with 1,500 numbers. Ensure that your array has 300 rows and 5
columns. 

In [1]:
import numpy as np
myarray = np.arange(1500).reshape(300,5)

b) Using slicing, split this array into 5 separate arrays. The number of rows in each array should be
equal, and there should still be 5 columns.


In [3]:
myarray1 = myarray[0:50,:]
myarray2 = myarray[50:100,:]
myarray3 = myarray[100:150,:]
myarray4 = myarray[150:200,:]
myarray5 = myarray[200:250,:]
myarray1

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54],
       [ 55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64],
       [ 65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74],
       [ 75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84],
       [ 85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94],
       [ 95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104],
       [105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114],
       [115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124],
       [125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134],
       [135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144],
       [145, 1

c) Reshape these 3 of these arrays into any dimensions of your choice. They should all have different
dimensions.

In [11]:
reshaped1 = myarray1.ravel()
reshaped2 = myarray2.reshape(125,2)
#reshaped3 = myarray3.reshape(3,50,2)
reshaped4 = myarray3.reshape(10,5,5)
reshaped2
reshaped4

array([[[500, 501, 502, 503, 504],
        [505, 506, 507, 508, 509],
        [510, 511, 512, 513, 514],
        [515, 516, 517, 518, 519],
        [520, 521, 522, 523, 524]],

       [[525, 526, 527, 528, 529],
        [530, 531, 532, 533, 534],
        [535, 536, 537, 538, 539],
        [540, 541, 542, 543, 544],
        [545, 546, 547, 548, 549]],

       [[550, 551, 552, 553, 554],
        [555, 556, 557, 558, 559],
        [560, 561, 562, 563, 564],
        [565, 566, 567, 568, 569],
        [570, 571, 572, 573, 574]],

       [[575, 576, 577, 578, 579],
        [580, 581, 582, 583, 584],
        [585, 586, 587, 588, 589],
        [590, 591, 592, 593, 594],
        [595, 596, 597, 598, 599]],

       [[600, 601, 602, 603, 604],
        [605, 606, 607, 608, 609],
        [610, 611, 612, 613, 614],
        [615, 616, 617, 618, 619],
        [620, 621, 622, 623, 624]],

       [[625, 626, 627, 628, 629],
        [630, 631, 632, 633, 634],
        [635, 636, 637, 638, 639],
        [6

d) Split 2 of these reshaped arrays vertically.

In [13]:
split1 = np.vsplit(myarray2,2)
split2 = np.vsplit(myarray4,5)
split2

[array([[750, 751, 752, 753, 754],
        [755, 756, 757, 758, 759],
        [760, 761, 762, 763, 764],
        [765, 766, 767, 768, 769],
        [770, 771, 772, 773, 774],
        [775, 776, 777, 778, 779],
        [780, 781, 782, 783, 784],
        [785, 786, 787, 788, 789],
        [790, 791, 792, 793, 794],
        [795, 796, 797, 798, 799]]),
 array([[800, 801, 802, 803, 804],
        [805, 806, 807, 808, 809],
        [810, 811, 812, 813, 814],
        [815, 816, 817, 818, 819],
        [820, 821, 822, 823, 824],
        [825, 826, 827, 828, 829],
        [830, 831, 832, 833, 834],
        [835, 836, 837, 838, 839],
        [840, 841, 842, 843, 844],
        [845, 846, 847, 848, 849]]),
 array([[850, 851, 852, 853, 854],
        [855, 856, 857, 858, 859],
        [860, 861, 862, 863, 864],
        [865, 866, 867, 868, 869],
        [870, 871, 872, 873, 874],
        [875, 876, 877, 878, 879],
        [880, 881, 882, 883, 884],
        [885, 886, 887, 888, 889],
        [890, 89

**Question 3**

Given the following string:

All I want is a proper cup of coffee<br>
Made in a proper copper coffee pot<br>
I may be off my dot<br>
But I want a cup of coffee<br>
From a proper coffee pot<br>
Tin coffee pots and iron coffee pots<br>
They’re no use to me<br>
If I can’t have a proper cup of coffee<br>
In a proper copper coffee pot<br>
I’ll have a cup of tea

a) Write a single function that uses regular expressions to highlight the words “tea”,“dot” or “pot” if they appear at the end of a line.

Your answer should look like this:

All I want is a proper cup of coffee<br>
Made in a proper copper coffee {pot}<br>
I may be off my {dot}<br>
But I want a cup of coffee<br>
From a proper coffee {pot}<br>
Tin coffee pots and iron coffee pots<br>
They’re no use to me<br>
If I can’t have a proper cup of coffee<br>
In a proper copper coffee {pot}<br>
I’ll have a cup of {tea}

In [14]:
import re
text = '''All I want is a proper cup of coffee
Made in a proper copper coffee pot
I may be off my dot
But I want a cup of coffee
From a proper coffee pot
Tin coffee pots and iron coffee pots
They’re no use to me
If I can’t have a proper cup of coffee
In a proper copper coffee pot
I’ll have a cup of tea
'''
print(re.compile(r'tea|dot|pot$',re.M).sub('{\g<0>}',text.rstrip()))

All I want is a proper cup of coffee
Made in a proper copper coffee {pot}
I may be off my {dot}
But I want a cup of coffee
From a proper coffee {pot}
Tin coffee pots and iron coffee pots
They’re no use to me
If I can’t have a proper cup of coffee
In a proper copper coffee {pot}
I’ll have a cup of {tea}


b) Using regular expressions, write code to highlight all words except “cup”, “pot” and “coffee” regardless of wherever it is found in passage.

Your answer should look like this:

{All} {I} {want} {is} {a} {proper} cup {of} coffee<br>
{Made} {in} {a} {proper} {copper} coffee pot<br>
{I} {may} {be} {off} {my} {dot}<br>

and so on.

In [ ]:
print(re.compile(r'\b(?!coffee|cup|pot\b)\w+',re.M).sub('{\g<0>}',text.rstrip()))